//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _5032Assignment_1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Booking
    {
        public int BookingId { get; set; }
        public string ClientClientId { get; set; }
        public string StaffStaffId { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Staff Staff { get; set; }
    }
}
